---
- name: Configure the Buildkite APT key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80
           id=32A37959C2FA5C3C99EFBC32A79206696452D198
           state=present

- name: Configure the Buildkite APT repository
  apt_repository: repo="deb https://apt.buildkite.com/buildkite-agent stable main"
                  state=present

- name: Install Buildkite Agent
  apt: pkg=buildkite-agent state=present

- name: Configure Buildkite
  template: src=buildkite-agent.cfg.j2
            dest="{{ buildkite_agent_conf_dir }}/buildkite-agent.cfg"
            owner=buildkite-agent
            group=buildkite-agent
            mode=0600
  notify:
    - Restart Buildkite
